image: docker:git
services:
  - docker:dind
before_script:
  - apk add --update bash coreutils tar curl
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master

dashing-main:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=dashing ROS_REPO=main

dashing-testing:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=dashing ROS_REPO=testing

eloquent-main:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=eloquent ROS_REPO=main

eloquent-testing:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=eloquent ROS_REPO=testing

