sudo: required
language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO="dashing"
    - DOCKER_IMAGE='osrf/ros:dashing-desktop'

before_install:
  - sudo apt-get -y ros-dashing-rqt-gui-cpp
  - pip3 install opcua
  - pip3 install socketserver

install:
  - git clone --depth=1 -b master https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
